WIDTH=1400
HEIGHT=1100
MAX_SCORE=10
# AI_STRENGTH: 1=Beginner, 2=Semi, 3=Professional , 4=Ultimate
AI_STRENGTH=4
LEFT_PLAYER=Left Player
RIGHT_PLAYER=Right Player
SOUNDS_ENABLED=on
# Press M to mute or unmute background music
MUSIC_ENABLED=on
